### ISSUE TITLE
Correccion

### ISSUE THREAD

**Issue by MLAGANGA** [MLAGANGA/tpbefunge#1]

**Comment by MLAGANGA** [comment]
Buenos días profe! Hacemos entrega de nuestro proyecto, en el readme nombre y padrón de los integrantes y forma en la que probamos el funcionamiento del código. Un saludo!

**Comment by MLAGANGA** [comment]
Buenas profe! Hacemos entrega de la versión del proyecto. En el readme datos de los integrantes y método de prueba y ejecución que usamos para probar el intérprete.

**Comment by smaraggi** [comment]
Hola chicos, acabo de revisar su TP.

Está bastante bien, pero tenemos que resolver estos dos detalles para cumplir los criterios de aprobación:

1) Uso de atom

No tienen que usar atom. Atom se usa para definir referencias mutables que se puedan modificar de manera segura entre distintos hilos, garantizando que las operaciones de actualización sean atómicas y que no haya condiciones de carrera.

En la programación estrictamente funcional, se evita el estado mutable. El uso de atom introduce mutabilidad, lo cual va en contra de los principios de la programación funcional pura. Además, en un entorno de un solo hilo no hay necesidad de utilizar mecanismos de concurrencia como atom, ya que no hay otros hilos con los que sincronizar. Para mantener la pureza funcional, es mejor usar estructuras de datos inmutables y funciones puras. En lugar de actualizar un atom, puedes retornar nuevas versiones de datos inmutables.

2) Problema en el archivo "palinqn.bf"

Este archivo corre mal en su intérprete: queda emitiendo caracteres de barra invertida (\) todo el tiempo. Los demás andan bien, así que tienen que investigar qué condición de este programa genera ese problema para resolverlo. El programa estaba en la lista de ejemplos que tienen que correr para darlo por aprobado, fíjense los archivos que son seis. El resultado esperado de este programa (palinqn) es que se imprima por pantalla el contenido del archivo.

**Comment by MLAGANGA** [comment]
Hola santi! Buenísimo, tendremos en cuenta los errores a corregir y ya nos pondremos a modificarlos. Gracias!

**Comment by smaraggi** [comment]
Agrego el punto 3 que me olvidé de mencionar, pero es una pavada.

3) Ejecución desde leiningen por terminal

Tienen que configurar el TP para que se pueda correr con el comando lein run directamente (con el path del archivo como parámetro adicional y obligatorio). Para esto podían configurar desde cero el proyecto con leiningen, pero sino pueden agregar esta línea al archivo del proyecto (project.clj) antes de cerrar el último paréntesis, de manera que quede, en vez de como está ahora:

```
...
  :repl-options {:init-ns tpbefunge.core})
```

de esta manera:
```
...
  :repl-options {:init-ns tpbefunge.core}
  :main tpbefunge.core)
```

De esa manera le especifican a lein cual es la función main para correr.

Prueben ustedes correrlo desde su PC con leiningen directamente. Tienen que tener configurado el path a su instalación de leiningeng (tienen instrucciones detalladas del setup, tiene un script todo automático). Yo hice esto y ya funciona, agréguenlo al repo como configuración requerida por favor.

**Comment by MLAGANGA** [comment]
Buenas santi! Todo bien? Ya modificamos los errores y corregimos el proyecto para que corra según lo marcado. 
 Quedamos a disposición, gracias!!

**Comment by smaraggi** [comment]
Hola chicos, bueno, hechas la correcciones ahora sí está aprobado el TP, les queda de nota 8 (ocho).

Tuve que corregir de nuevo el archivo de proyecto para que se pueda correr con el comando "lein run" desde afuera del IDE. Ustedes tenían esta línea en el archivo de proyecto:

:main tpbefunge.core

Pero debía decir, según los archivos:

:main tpbefunge.main

Además, hay un corte prematuro del programa en los archivos "life.bf" y "maze.bf". Veo que definieron una constante max-iter para cortar bucles infinitos de ejecución (o muy largos). En este caso entiendo que fue idea de ustedes porque no estaba pedido. Esto sí modifica el comportamiento esperado del programa, porque corta antes de tiempo como decía. Si el programa tiene que quedar corriendo ad-infinitum, ustedes como intérprete de un lenguaje deberían seguir corriendo hasta que el usuario o el sistema operativo corten el proceso, o que el programa llegue a su fin naturalmente por alguna condición interna. Imagínense si python dijera bueno listo, no itero más, y se termina el programa. Igual no le di mucha importancia a esto porque es algo que agregaron ustedes con un criterio propio y no un error por algo no contemplado, y sobre todo que sería muy fácil de arreglar también una vez hecho el comentario.

Con estos comentarios ya queda listo y aprobado el TP. Felicitaciones y buen cierre de cuatrimestre.
